### ISSUE TITLE
Improvement: Add cluster name to assessment reports

### ISSUE THREAD

**Issue by mpermar** [vmware-tanzu/cloud-native-security-inspector#135]
**Is your feature request related to a problem? Please describe.**

Assessment reports today don't include cluster names. It would be nice to have it so that in multi-cluster scenarios the user can immediately know where the assesment reports are coming from.

**Describe the solution you'd like.**

I'd like the assessment reports to contain the name of the cluster. There might be other cluster information that can be useful here for other use cases, and this might be a good chance to add that too.

**Comment by JingChen23** [comment]
Thanks for proposing the issue, now the initial requirement has been resolved by the new scanner proposed in #213 , you can add whatever you want in the new scanner. Thus we can close this issue.
