### ISSUE TITLE
Improvement: Add pod labels to Assessment Reports

### ISSUE THREAD

**Issue by mpermar** [vmware-tanzu/cloud-native-security-inspector#136]
**Is your feature request related to a problem? Please describe.**

Assessment reports today don't include pod labels. Pod labels can potentially be used by systems that process assessment reports to match those assessments better to customer workloads through different criteria. For example, on large microservice architectures some teams might decide to add certain tags to the pods as labels, e.g. keywords identifying the owning teams or some other internal metadata that makes sense to the customer. 

**Describe the solution you'd like.**

I would like to have pod labels included in the assessment reports.

**Comment by JingChen23** [comment]
Thanks for proposing the issue, now the initial requirement has been resolved by the new scanner proposed in https://github.com/vmware-tanzu/cloud-native-security-inspector/pull/213 , you can add whatever you want in the new scanner. Thus we can close this issue.
