### ISSUE TITLE
Can not create a secret using the portal after fresh installation

### ISSUE THREAD

**Issue by 4everming** [vmware-tanzu/cloud-native-security-inspector#221]
**Environment**
Platform: [KIND]
Kubernetes/Platform Version(s): 
v1.24.0

**Describe the bug**
Cannot create a secret for Harbor successfully after the fresh installation.

**To Reproduce**
1. Go to 'Setting' menu
2. Click on 'Secret' tab
3. Click on 'New' button
4. Fill out all the fields needed 
5. Click on the create button.

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior.

**Screenshots**
<img width="1818" alt="image" src="https://user-images.githubusercontent.com/12963596/226407891-835f02af-6fa3-4d3d-aa88-2eb210bdad5d.png">

**Versions:**
Please specify the versions of following systems.

- Kubernetes version: [1.24.0]
- CNSI version: [v0.3.0 and main]

**UI Issue**
Desktop (please complete the following information):**
 - OS: [MacOs]
 - Browser [chrome]

**Additional context**
Can reproduce both on main branch and tag v0.3.0

**Comment by JingChen23** [comment]
Has been resolved in version > 0.3
