### ISSUE TITLE
UI Bug: The UI for creating setting has a fake-optional for VAC settings

### ISSUE THREAD

**Issue by JingChen23** [vmware-tanzu/cloud-native-security-inspector#246]
![Screenshot 2023-06-05 at 10 03 26](https://github.com/vmware-tanzu/cloud-native-security-inspector/assets/15973672/b86dc1a4-ae21-4b25-b861-2cc463a57f12)

The VAC setting should be optional but I cannot click next with nothing filled.

**Comment by qijianshuai** [comment]
Fixed in pr#248

**Comment by qijianshuai** [comment]
Fixed in pr#248
